### ISSUE TITLE
Error using wildcards to import stations

### ISSUE THREAD

**Issue by EzioDAlema** [INGV/qquake#67]
When I import station data using special characters ("*" "," ) there appears to be an error in the map, but the link to the EIDA service is correct.
For example, if I want to import the data of all the stations with initials starting with A and those with B for the IV network, I get the string:
  `http://webservices.ingv.it/fdsnws/station/1/query?station=A*, B*&network=IV&format=xml`
which is correct.
If I import the data into my project I get the stations only of the stations entered first in the query, then the A*.
The Layer created correctly shows the data table, but only for stations A*, while stations B* do not exist.

**Comment by MarioLocati** [comment]
I see no issue related to QQuake here.
The issue lies in the space after the comma you put in the condition "station=A*, B*", whereas it should be"station=A*,B*".
Once stripped off the space, I can confirm QQuake receive both stations beginning with A and with B.

![image](https://github.com/INGV/qquake/assets/20398568/f192ae05-cac9-49ae-9680-3f4caa4a2bd8)

@EzioDAlema thank you for the feedback, I have added the patch https://github.com/INGV/qquake/commit/c3dfa39d31166dc71c98001e739b02d89e306cc4 to ensure that all spaces provided by the users in the network, station and location conditions are ignored.

Please, close this issue if you considered it solved.
